apiVersion: v1
kind: Service
metadata:
  name: multi-cdn-demo-web
  namespace: multi-cdn-demo
spec:
  type: LoadBalancer
  selector:
    app: multi-cdn-demo-web
  ports:
    - name: http
      port: 80
      targetPort: 80
