apiVersion: v1
kind: Secret
metadata:
  name: multi-cdn-adapter-credentials
  namespace: multi-cdn-demo
stringData:
  cloudflare-api-token: "REPLACE_WITH_CLOUDFLARE_API_TOKEN"
  cloudflare-zone-name: "milionmonkee.win"
  cloudflare-zone-id: "REPLACE_WITH_CLOUDFLARE_ZONE_ID"
  akamai-client-secret: "REPLACE_WITH_AKAMAI_CLIENT_SECRET"
  akamai-host: "REPLACE_WITH_AKAMAI_HOST"
  akamai-access-token: "REPLACE_WITH_AKAMAI_ACCESS_TOKEN"
  akamai-client-token: "REPLACE_WITH_AKAMAI_CLIENT_TOKEN"
