apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-state
  namespace: multi-cdn-demo
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
